# -----------------------------------------------------------------------------
# @author    Auto-generated by STM32CubeIDE for Visual Studio Code Extension
# -----------------------------------------------------------------------------
# @attention
#
# Copyright (c) 2025 STMicroelectronics.
# All rights reserved.
#
# This software is licensed under terms that can be found in the LICENSE file
# in the root directory of this software component.
# If no LICENSE file comes with this software, it is provided AS-IS.
#
# -----------------------------------------------------------------------------

# This is converter generated file, and shall not be touched by user
#
# Use CMakeLists.txt to apply user changes
cmake_minimum_required(VERSION 3.20)

# Core MCU flags, CPU, instruction set and FPU setup
set(cpu_PARAMS ${cpu_PARAMS} ${CPU_FLAGS})

# Linker script
set(linker_script_SRC ${linker_script_SRC}
    ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/STM32F746NGHX_FLASH.ld
)

# # Sources
# set(sources_SRCS ${sources_SRCS}
#     # Core sources
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Src/main.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Src/stm32f7xx_hal_msp.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Src/stm32f7xx_it.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Src/syscalls.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Src/sysmem.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Src/system_stm32f7xx.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Startup/startup_stm32f746nghx.s

#     # HAL driver sources (only the ones present in tree)
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cortex.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_dma_ex.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_exti.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_flash_ex.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_gpio.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_i2c_ex.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_pwr_ex.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc.c
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_rcc_ex.c
# )

# # Include directories
# set(include_c_DIRS ${include_c_DIRS}
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Core/Inc
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/STM32F7xx_HAL_Driver/Inc
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/CMSIS/Device/ST/STM32F7xx/Include
#     ${CMAKE_CURRENT_SOURCE_DIR}/ide_gen/Drivers/CMSIS/Include
# )
# set(include_cxx_DIRS ${include_cxx_DIRS}
# )
# set(include_asm_DIRS ${include_asm_DIRS}
# )

# # Symbols definition
# set(symbols_c_SYMB ${symbols_c_SYMB}
#     USE_HAL_DRIVER
#     STM32F746xx
# )
# set(symbols_cxx_SYMB ${symbols_cxx_SYMB}
# )
# set(symbols_asm_SYMB ${symbols_asm_SYMB}
# )

# # Link directories
# set(link_DIRS ${link_DIRS}
# )

# # Link libraries
# set(link_LIBS ${link_LIBS}
# )

# # Compiler options
# set(compiler_OPTS ${compiler_OPTS})

# # Linker options
# set(linker_OPTS ${linker_OPTS})
